name: Deploy Ansible

on: 
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Deploy Ansible
              uses: ./.github/actions/ansible
              env:
                ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
                AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
                AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                AZURE_SECRET: ${{ secrets.AZURE_SECRET }}